# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.IntegerField(choices=[(0, 'curs'), (1, 'laborator'), (1, 'seminar')])),
                ('nume_obiect', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nume obiect')),
                ('color', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nume obiect')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='absente',
            name='materie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absente.SchoolObject'),
        ),
        migrations.AddField(
            model_name='absente',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
