# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absente',
            old_name='end_date',
            new_name='end',
        ),
    ]
