# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absente', '0002_auto_20170831_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absente',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='absente',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schoolobject',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='schoolobject',
            name='disciplina',
            field=models.IntegerField(choices=[(0, 'curs'), (1, 'laborator'), (2, 'seminar')]),
        ),
    ]
