# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alert_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alert_sms',
        ),
    ]
