# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170422_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='university')),
                ('faculty', models.CharField(blank=True, max_length=40, null=True, verbose_name='faculty')),
                ('specialization', models.CharField(blank=True, max_length=40, null=True, verbose_name='specialization')),
                ('study_program', models.IntegerField(choices=[(0, 'Licenta'), (1, 'Masterat')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='second email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='promotia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
