# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cnp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='promotia',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email2',
            new_name='second_email',
        ),
    ]
