# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170423_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name of activity domain')),
            ],
        ),
    ]
