# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activitydomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='activity_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ActivityDomain'),
            preserve_default=False,
        ),
    ]
