# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_university_activity_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
    ]
